script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix test && git push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.10.2
otp_release: 22.3
services:
  - postgresql
before_script:
  - PGPASSWORD=postgres psql -c 'create database portfolio_test;' -U postgres
